#rEFInd-Minimalistic-Theme
#Modified_By_iammrmehedi


#ICON
icons_dir themes/rEFInd-Minimalistic-Theme/icons


#BACKGROUND_IMAGE
banner themes/rEFInd-Minimalistic-Theme/background.png
banner_scale fillscreen


#SELECTION_IMAGE
selection_big   themes/rEFInd-Minimalistic-Theme/selection_big.png
selection_small themes/rEFInd-Minimalistic-Theme/selection_small.png


#TOOLS
#showtools reboot, shutdown
#hideui singleuser,hints,arrows,label,badges


#MENUENTRIES

menuentry "Windows 11 Pro" {
	icon /EFI/refind/themes/rEFInd-Minimalistic-Theme/icons/os_win11.png
    	volume "e7dedaad-8c1e-4fe8-a1a7-2d06a1e3de03"
        loader /EFI/Microsoft/Boot/bootmgfw.efi
	#disabled
}
menuentry "Arch" {
    icon /EFI/refind/themes/rEFInd-Minimalistic-Theme/icons/os_arch.png
    #volume /dev/nvme0n1p7
    loader /vmlinuz-linux
    #initrd /initramfs-linux.img
    options "rw root=/dev/nvme0n1p7 add_efi_memmap initrd=\initramfs-linux.img"
    #disabled
}
