# Font sizes
font_h1 = 20
font_h2 = 16
font_h3 = 14
font_regular = 16
font_small = 12

# Colors for text
text_color = rgba(ffffffea)
bright_text_color = rgba(ffffffff)
accent_color = rgba(ff66ccff)
font_family = FiraCode Nerd Font
